name: Node build

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  build-folder:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Install, build, test
      run: |
        npm install
        npm run build
      env:
        CI: true
