name: Super-Linter

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1

        with:
          node-version: ${{ matrix.node-version }}
      - name: Install App
        run: |
          npm install
        env:
          CI: true
      - name: Run ES linter
        run: |
          npm run eslint
      - name: Run Style SCSS linter
        run: |
          npm run scsslint