name: Node build

# Run this workflow every time a new commit pushed to your repository
on: [push]

jobs:
  build-folder:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build
      run: |
        npm install
        npm run build
      env:
        CI: true